Problem 3
Part a)

In [16]:
import numpy as np
from fractions import Fraction

# Create matrices W1 and W2
W1 = np.array([[1.00, 0.50, 0.30, 0.10, 0.10],
               [0.50, 1.00, 0.40, 0.10, 0.10],
               [0.30, 0.40, 1.00, 0.30, 0.30],
               [0.10, 0.10, 0.30, 1.00, 0.50],
               [0.10, 0.10, 0.30, 0.50, 1.00]])

W2 = np.array([[1.00, 0.20, 0.50, 0.10, 0.10],
               [0.20, 1.00, 0.30, 0.10, 0.10],
               [0.50, 0.30, 1.00, 0.30, 0.30],
               [0.10, 0.10, 0.30, 1.00, 0.50],
               [0.10, 0.10, 0.30, 0.50, 1.00]])

# Create the normalized weight matrix P1 and P2

def normalized_weight_matrix(weight_matrix):
    W = weight_matrix
    P = np.empty((W.shape[0], W.shape[1]))
    for i in range(W.shape[0]):
        for j in range(W.shape[1]):
            if(j == i):
                 
                P[i,j] = 0.5 
            else: 
                sum = 0
                for k in range(W.shape[0]):
                    if k != i:
                        sum += W[i,k]
                
                P[i,j] = (W[i,j]) / (2 * sum)
    return P




Thus we have the matrices P1 and P2:

In [18]:
print("Matrix P1:") 
print(normalized_weight_matrix(W1))
print("Matrix P2:")
print(normalized_weight_matrix(W2))

Matrix P1:
[[0.5        0.25       0.15       0.05       0.05      ]
 [0.22727273 0.5        0.18181818 0.04545455 0.04545455]
 [0.11538462 0.15384615 0.5        0.11538462 0.11538462]
 [0.05       0.05       0.15       0.5        0.25      ]
 [0.05       0.05       0.15       0.25       0.5       ]]
Matrix P2:
[[0.5        0.11111111 0.27777778 0.05555556 0.05555556]
 [0.14285714 0.5        0.21428571 0.07142857 0.07142857]
 [0.17857143 0.10714286 0.5        0.10714286 0.10714286]
 [0.05       0.05       0.15       0.5        0.25      ]
 [0.05       0.05       0.15       0.25       0.5       ]]


In [ ]:
# Similarity Matrix

def similarity_matrix(weight_matrix):
    return 0
